language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - composer validate
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  